# Generated by Django 4.2.10 on 2024-02-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_feeding_options_feeding_satisfied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeding',
            name='satisfied',
        ),
    ]
