# Generated by Django 4.2.10 on 2024-02-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='weapons',
            field=models.ManyToManyField(to='main_app.weapon'),
        ),
    ]
